spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/student-db
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

elasticsearch:
  host: localhost
  port: 9200
  index-prefix: logs
  api-key: your-api-key

logging:
  controller:
    logger-type: ELASTICSEARCH